### ISSUE TITLE
Installation is looking for setup

### ISSUE THREAD

**Issue by Mr-Ruben** [sinkingtitanic/qlogging#2]
Hello,

I just did what the homepage says one should do.

```
import qlogging
logger = qlogging.get_logger(level='debug')

logger.debug("This is debug") 
logger.info("This is info")
logger.warning("This is warning")
logger.error("This is an error")
logger.critical("This is a critical")

```
and it fails with
```

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/qlogging/__init__.py", line 2, in <module>
    from setup import __version__
ModuleNotFoundError: No module named 'setup'
```

![](https://i.imgur.com/MZweCM4.png)

In github I can see the setup.py file, but something is not working as expected. Please forgive my ignorance.

**Comment by Mr-Ruben** [comment]
If I run a second time

```
!pip install qlogging
import qlogging

```

```

Requirement already satisfied: qlogging in /usr/local/lib/python3.7/dist-packages (1.2.3)
Requirement already satisfied: colorama in /usr/local/lib/python3.7/dist-packages (from qlogging) (0.4.4)
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-26-1f1a0c2325e4> in <module>()
      3 get_ipython().system('pip install qlogging')
      4 #!pip install setup
----> 5 import qlogging

/usr/local/lib/python3.7/dist-packages/qlogging/__init__.py in <module>()
      1 from .qlogging import get_logger, config
----> 2 from setup import __version__

ModuleNotFoundError: No module named 'setup'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------
```
